[package]
name = "api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1.0.139"
karics = { git = "https://github.com/kanari-network/karics.git"}